---
- name: Mise a jour apt
  apt:
    update_cache: yes
    upgrade: dist
  ignore_errors: yes

- name: Paquets communs LOGISTIA
  apt:
    name:
      - qemu-guest-agent
      - curl
      - wget
      - git
      - vim
      - htop
      - net-tools
      - ca-certificates
      - gpg
      - python3
      - python3-pip
      - rsyslog
      - sudo
    state: present
    update_cache: yes

- name: qemu-guest-agent actif
  systemd:
    name: qemu-guest-agent
    enabled: yes
    state: started
  ignore_errors: yes

- name: rsyslog vers soc-logistia
  lineinfile:
    path: /etc/rsyslog.conf
    line: "*.* @10.40.40.10:514"
    state: present
  when: inventory_hostname != 'soc-logistia'
  notify: restart rsyslog
