---
- name: Configuration commune toutes machines LOGISTIA
  hosts: all
  become: true
  roles:
    - logistia-common

- name: Durcissement securite CIS L1
  hosts: all
  become: true
  roles:
    - logistia-hardening

- name: router-logistia — NAT nftables interfaces VLAN
  hosts: logistia-routers
  become: true
  roles:
    - logistia-router

- name: app-logistia — Nginx Dolibarr Traccar
  hosts: logistia-apps
  become: true
  roles:
    - logistia-app

- name: db-logistia — MariaDB VLAN Data
  hosts: logistia-databases
  become: true
  roles:
    - logistia-db

- name: devops-logistia — GitHub Runner Terraform Ansible
  hosts: logistia-devops
  become: true
  roles:
    - logistia-devops

- name: soc-logistia — Wazuh Prometheus Grafana Syslog
  hosts: logistia-soc
  become: true
  roles:
    - logistia-soc

- name: misp-logistia — CTI MISP via Docker
  hosts: logistia-misp
  become: true
  roles:
    - logistia-misp
- name: cortex-logistia — Cortex analyzers + Elasticsearch
  hosts: logistia-cortex
  become: true
  roles:
    - logistia-cortex
- name: thehive-logistia — SOAR TheHive + Cassandra + ES + MinIO
  hosts: logistia-thehive
  become: true
  roles:
    - logistia-thehive
- name: ia-logistia — Ollama Mistral logistia-scanner
  hosts: logistia-ia
  become: true
  roles:
    - logistia-ia

- name: backup-logistia — rsync PBS 3-2-1
  hosts: logistia-backup
  become: true
  roles:
    - logistia-backup

- name: Verification finale infrastructure LOGISTIA
  hosts: all
  become: true
  tasks:
    - name: qemu-guest-agent actif sur toutes les machines
      service:
        name: qemu-guest-agent
        state: started
        enabled: true
