---
- name: reload nftables
  command: nft -f /etc/nftables.conf

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: reload sysctl
  command: sysctl --system
  changed_when: false

- name: reload systemd
  systemd:
    daemon_reload: true
